#
# Copyright (c) 2025 anglinAI
# 
# This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
# To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/
# or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
# 
# You are free to:
# - Share — copy and redistribute the material in any medium or format
# - Adapt — remix, transform, and build upon the material
# 
# Under the following terms:
# - Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made.
# - NonCommercial — You may not use the material for commercial purposes.
# - ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license.
# 
# No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
#

name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            react/package-lock.json
            functions/package-lock.json

      - name: Install React dependencies
        working-directory: ./react
        run: npm ci

      - name: Build React app
        working-directory: ./react
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_FUNCTIONS_URL: ${{ secrets.VITE_FIREBASE_FUNCTIONS_URL }}

      - name: Install Firebase Functions dependencies
        working-directory: ./functions
        run: npm ci

      - name: Deploy to Firebase (PR Preview)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: pr-${{ github.event.pull_request.number }}
          expires: 7d
          entrypoint: ./react

      - name: Deploy to Firebase (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
          entrypoint: ./react

      - name: Deploy Firebase Functions
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
          npm install -g firebase-tools
          firebase deploy --only functions --non-interactive --project ${{ secrets.FIREBASE_PROJECT_ID }}
        working-directory: ./

      - name: Deploy Firestore Rules
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
          firebase deploy --only firestore:rules --non-interactive --project ${{ secrets.FIREBASE_PROJECT_ID }}
        working-directory: ./

      - name: Deploy Storage Rules
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
          firebase deploy --only storage --non-interactive --project ${{ secrets.FIREBASE_PROJECT_ID }}
        working-directory: ./